[package]
authors = ["huisedenanhai <winser@pku.edu.cn>"]
edition = "2018"
name = "cpu"
version = "0.1.0"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
remotery-rs = {path = "../.."}
